# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Идентификатор товара"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Только для админки, пользователю не показывается",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Донат-товар",
                "verbose_name_plural": "Донат-товары",
                "ordering": ["product_id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=10,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "store_transaction_id",
                    models.CharField(
                        max_length=255, verbose_name="ID транзакции в сторе"
                    ),
                ),
                (
                    "purchase_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Нужен повторно для acknowledge; для iOS не используется",
                        verbose_name="Токен покупки (Android)",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Заполнено, только пока покупка не привязана к пользователю",
                        max_length=64,
                        verbose_name="ID устройства (анонимно)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Подтверждено стором"),
                            ("completed", "Завершено"),
                            ("refunded", "Возвращено"),
                            ("revoked", "Отозвано"),
                        ],
                        default="verified",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Apple's Sandbox/Production/Xcode/LocalTesting from the "
                            "verified transaction. Apple explicitly falls back to "
                            "verifying Sandbox transactions in production for App "
                            "Review, so this is how staff tell a real donation from "
                            "a free sandbox one. Left blank for Android, which has "
                            "no equivalent concept on this endpoint."
                        ),
                        max_length=20,
                        verbose_name="Окружение стора",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырой ответ стора"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Подтверждено"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="donations.donationproduct",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка (донат)",
                "verbose_name_plural": "Покупки (донаты)",
                "ordering": ["-verified_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "store_transaction_id"),
                        name="unique_platform_transaction",
                    )
                ],
            },
        ),
    ]
