# SPDX-FileCopyrightText: 2025 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.8 on 2025-11-30 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "musical_title",
                    models.CharField(
                        max_length=50, verbose_name="Музыкальное название"
                    ),
                ),
                (
                    "order_in_note",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "start_fret",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="С какого лада начинается"
                    ),
                ),
                (
                    "has_barre",
                    models.BooleanField(default=False, verbose_name="Есть барре?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChordPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "string_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Номер струны",
                    ),
                ),
                ("fret", models.SmallIntegerField(verbose_name="На каком ладу зажата")),
                (
                    "finger",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Каким пальцем зажата",
                    ),
                ),
                (
                    "chord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="chords.chord",
                    ),
                ),
            ],
            options={
                "ordering": ["string_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chord", "string_number"),
                        name="unique_chord_string_number",
                    )
                ],
            },
        ),
    ]
