# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.8 on 2026-01-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chords", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chordposition",
            name="finger",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Каким пальцем зажата",
            ),
        ),
        migrations.AlterField(
            model_name="chordposition",
            name="fret",
            field=models.SmallIntegerField(
                help_text="0 - открыта, -1 - заглушена",
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="На каком ладу зажата",
            ),
        ),
    ]
