# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 5.2.8 on 2026-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Позволяет указать, для какого именно урока и что это за рисунок",
                        max_length=20,
                        unique=True,
                        verbose_name="Кодовое название",
                    ),
                ),
                (
                    "inscription",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Надпись"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        max_length=255,
                        upload_to="lesson_schemes/",
                        verbose_name="Изображение",
                        width_field="width",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бой или схема (рисунок)",
                "verbose_name_plural": "Бои или схемы (рисунки)",
            },
        ),
    ]
